[package]
name = "todo-cli"
version = "0.1.0"
edition = "2018"

[features]

[dependencies]
chrono = "0.4.19"
serde_json = "1.0.78"
structopt = "0.3.26"

[dependencies.serde] 
version = "1.0"
features = ["derive"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]
